name: niche_ai_companion
description: A Niche AI Companion app for mental coaching.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.1
  firebase_messaging: ^15.2.1
  flutter_riverpod: ^2.6.1
  google_generative_ai: ^0.4.6
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/system_prompt.txt
